[in progress] Bugfix/wf 688  auth error in container
Backbase/golden-sample-app pull request #37
Opened 2022-04-01 07:26 UTC by yenobi

- [ ] pr is not finished yet

2022-04-01 07:27 UTC, yenobi commented
The registry was changed temporarily due to the missing of one of the widgets, used in the app. Need to check, how to fix it

2022-04-01 07:30 UTC, yenobi commented
What is left for the moment of creating PR:
the redirect URI has the wrong value and identity validation did not allow such a redirect.

The value is `http://localhost:4200${PATHNAME}transactions`, but should be something like `http://localhost:4200$/${BASE_HREF}/select-context` (might be not exactly the same).

2022-04-08 11:36 UTC, kirillsud commented
- [ ]  Merge after a new web-base version 0.0.17 will be released. This version contains support for API proxy

2022-05-10 07:56 UTC, santam85 commented
What is the error we are trying to fix here? We really cannot rely on proxying the API in web-base, as that would not be possible on a CDN, so I want to make sure there aren't other alternatives

2022-05-10 18:13 UTC, kirillsud commented
> What is the error we are trying to fix here? We really cannot rely on proxying the API in web-base, as that would not be possible on a CDN, so I want to make sure there aren't other alternatives

@santam85 I want to test `GSA` inside a Docker container based on `web-base` image

2022-05-10 18:18 UTC, kirillsud commented on apps/golden-sample-app/src/app/user-context/user-context.component.ts
> +(window as any).reloadPage = () => Promise.resolve();
Done

2022-06-29 12:38 UTC, santam85 requested changes
I don't want to exemplify reverse proxing of APIs in the golden sample. Shall I reject this one?

2022-07-26 11:11 UTC, closed without merging